#!/bin/sh
set -e

PKG=fstab.d

case "$1" in
  configure)

    ;;

  triggered)

        /usr/sbin/update-fstab

    ;;

  *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 0
    ;;
esac

#DEBHELPER#
